modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="MIT"

[[mods]] #mandatory

modId="nivadeus" #mandatory

version="0.0.1-1.18.2" #mandatory

displayName="Nivadeus" #mandatory

logoFile="examplemod.png" #optional

credits="[Something here]" #optional

authors="Ethan Greenwood and Happy Ta" #optional

description='''
Nivadeus is a mod for Minecraft (a 3-D computer game where
players can build anything. Minecraft is about building with blocks
and creating structures across various environments in a virtual
world. To accomplish this, the game involves resource gathering,
crafting items, building, and combat.) This mod will add to this a
new modular magic system, allowing the player the ability to craft
and conjure spells to augment their ability to partake in the
existing elements of the game. The spells are to be created by the
player modularly using predefined function nodes in a style similar
to a visual programming language, with connections drawn between the
nodes to define the sequence. These nodes will be unlocked in tiers
while progressing through the mod by playing.
'''

[[dependencies.nivadeus]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
    
# Here's another dependency
[[dependencies.nivadeus]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
